[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = false

[debug]
render_timer = false

[env]
TERM = "screen-256color"

[font]
size = 16

[font.normal]
style = "Regular"
family = "ComicShannsMono Nerd Font"

[font.italic]
style = "Regular Italic"
family = "ComicShannsMono Nerd Font"

[font.bold]
style = "Bold"
family = "ComicShannsMono Nerd Font"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true
option_as_alt = "OnlyLeft"
opacity = 1

[window.dimensions]
columns = 260
lines = 100

[window.padding]
x = 1
y = 1

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppucin-mocha.toml"]
