# Configuration for Alacritty, the GPU enhanced terminal emulator shamelessly copied from https://github.com/fatih/dotfiles
import:
 - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color

window:
  option_as_alt: OnlyLeft
  # Window dimensions in character columns and lines
  # (changes require restart)
  dimensions:
    columns: 160
    lines: 48

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 2
    y: 2

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  # Setting this to false will result in window without borders and title bar.
  decorations: "Buttonless"

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Monaco for Powerline
    style: Regular

  # The bold font face
  # bold:
  #   family: FiraCode Nerd Font
  #   style: Bold

  # # The italic font face
  # italic:
  #   family: FiraCode Nerd Font
  #   style: Regular Italic

  # Point size of the font
  size: 13.5

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 1

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  AppleFontSmoothing: true
debug:
  # Should display the render timer
  render_timer: false

# Colors (Tomorrow Night Bright)
# colors:
#   # Default colors
#   primary:
#     background: '0x24292e'
#     foreground: '0xd1d5da'
#
#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text:   '0xf1c1c1'
#     cursor: '0xff2600'
#
#   # Normal colors
#   normal:
#     black:   '0x586069'
#     red:     '0xea4a5a'
#     green:   '0x34d058'
#     yellow:  '0xffea7f'
#     blue:    '0x2188ff'
#     magenta: '0xb392f0'
#     cyan:    '0x39c5cf'
#     white:   '0xd1d5da'
#
#   # Bright colors
#   bright:
#     black:   '0x959da5'
#     red:     '0xf97583'
#     green:   '0x85e89d'
#     yellow:  '0xffea7f'
#     blue:    '0x79b8ff'
#     magenta: '0xb392f0'
#     cyan:    '0x56d4dd'
#     white:   '0xfafbfc'
#
#   indexed_colors:
#     - { index: 16, color: '0xd18616' }
#     - { index: 17, color: '0xf97583' }
#
#   # Dim colors (Optional)
#   dim:
#     black:   '0x333333'
#     red:     '0xf2777a'
#     green:   '0x99cc99'
#     yellow:  '0xffcc66'
#     blue:    '0x6699cc'
#     magenta: '0xcc99cc'
#     cyan:    '0x66cccc'
#     white:   '0xdddddd'

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
bell:
  animation: EaseOutExpo
  duration: 0

# Window opacity
window.opacity: 1.0

# Mouse bindings
#
# Currently doesn't support modifiers. Both the `mouse` and `action` fields must
# be specified.
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# Values for `action`:
# - Paste
# - PasteSelection
# - Copy (TODO)
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to both the primary and
  # the selection clipboard. Otherwise, it will only be copied to the selection
  # clipboard.
  save_to_clipboard: true

window.dynamic_title: true

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block
  unfocused_hollow: false

# Live config reload (changes require restart)
live_config_reload: true

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/zsh.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
# shell:
#   program: /bin/bash
#   args:
#     - --login
