local g = vim.g
local opt = vim.opt

g.mapleader = ','
g.maplocalleader = ','
g.have_nerd_font = true -- Enable Nerd Font icons for UI

opt.clipboard = 'unnamedplus' -- Sync clipboard with system
opt.number = true -- Show line numbers
opt.relativenumber = true -- Show relative line numbers
opt.cursorline = true -- Highlight current line
opt.scrolloff = 5 -- Context lines around cursor
opt.mouse = 'a' -- Enable mouse support
opt.termguicolors = true -- Enable true color
opt.linebreak = true -- Break lines at word boundaries
opt.breakindent = true -- Indent wrapped lines
opt.cmdheight = 2 -- Command line height
opt.undofile = true -- Persist undo history
opt.title = true -- Set window title
opt.spell = false -- Default off, controlled by autocmd
opt.spelllang = 'en_us,fr' -- Spell check languages
opt.display = 'lastline' -- Show last line even if truncated
opt.diffopt = 'internal,filler,closeoff,vertical' -- Diff settings
opt.splitright = true -- Vertical splits to the right
opt.splitbelow = true -- Horizontal splits below
opt.splitkeep = 'screen' -- Keep screen layout during splits
opt.expandtab = true -- Use spaces instead of tabs
opt.shiftwidth = 2 -- Size of indent
opt.tabstop = 2 -- Width of tabs
opt.softtabstop = 2 -- Soft tab width
opt.list = true -- Show invisible character
opt.backspace = { 'indent', 'eol', 'start' } -- Backspace behavior
opt.incsearch = true -- Incremental search
opt.hlsearch = true -- Highlight search matches
opt.ignorecase = true -- Case-insensitive search
opt.smartcase = true -- Smart case search
opt.gdefault = true -- Global substitute by default
opt.backup = false -- Disable backup files
opt.writebackup = false -- Disable write backup
opt.swapfile = false -- Disable swap files
opt.completeopt = 'menuone,noselect' -- Completion options
opt.updatetime = 300 -- Update time for LSP/cmp
opt.timeoutlen = 300 -- Keycode timeout
opt.signcolumn = 'yes' -- Always show sign column
opt.matchtime = 2 -- Match highlight duration
opt.matchpairs:append('<:>') -- Add <> to match pairs
opt.autoindent = true -- Auto-indent new lines
opt.smartindent = true -- Smart indenting
opt.guicursor = 'n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50' -- Custom cursor shapes
opt.fillchars = { eob = ' ', vert = '▏' } -- Clean fill characters
